### ISSUE TITLE
ToolingAPI.ToolingAPIException: INVALID_TYPE : sObject type ‘CustomEntityDefinition’ is not supported.

### ISSUE THREAD

**Issue by ghost** [afawcett/apex-toolingapi#19]
When a non-admin (it works for admins) calls those methods in a "with sharing" controller extension:

public String getRelatedListId() {
        String result = null;

```
        String soql = 'SELECT Id FROM CustomField WHERE DeveloperName = \'mdr_Travel\' AND TableEnumOrId = \'' + getExpenseObjectId() + '\'';
        List<ToolingAPI.CustomField> customFields = (List<ToolingAPI.CustomField>) toolingAPI.query(soql).records;

        if(customFields.size() == 1) {
                result = customFields.get(0).Id;
                result = result.Substring(0,15);
        }       

    return result;
}


private Id getExpenseObjectId() {
    Id result = null;

    String soql = 'SELECT Id FROM CustomObject WHERE DeveloperName = \'Expense\'';
            List<ToolingAPI.CustomObject> customObjects = (List<ToolingAPI.CustomObject>) toolingAPI.query(soql).records;

            if(customObjects.size() == 1) {
                    result = customObjects.get(0).Id;
            }

    return result;
}
```

he receives a

UP2GO_ITE.ToolingAPI.ToolingAPIException: INVALID_TYPE : sObject type ‘CustomEntityDefinition’ is not supported.
Class.UP2GO_ITE.ToolingAPI.submitRestCall: line 1841, column 1
Class.UP2GO_ITE.ToolingAPI.submitRestCall: line 1782, column 1
Class.UP2GO_ITE.ToolingAPI.submitRestCall: line 1774, column 1
Class.UP2GO_ITE.ToolingAPI.query: line 105, column 1
Class.UP2GO_ITE.TravelCtrlExt.getExpenseObjectId: line 125, column 1
Class.UP2GO_ITE.TravelCtrlExt.getRelatedListId: line 109, column 1

**Comment by msheehan79** [comment]
Hi all - was this issue ever added to the known issues list?  I too have run into this and wondering if this is due to be sorted anytime soon.

**Comment by priyapanigrahy** [comment]
Is there any update on this issue. We are still getting this issue.

**Comment by rdehler** [comment]
@afawcett I just encountered this.  This seems to be an issue large enough to make this entire package useless... you have to have View All Data on the user level, otherwise you get this error?  That severely limits the capabilities of this API.

**Comment by afawcett** [comment]
Yeah i think we should raise an Idea Exchange to see if this can be changed, see my update from the Tooling API developer earlier in this thread, there is perhaps some reasonable scope to allow this.

**Comment by up2go-rsoesemann** [comment]
While we are waiting for a solution by Salesforce.com (Is there any update here or at least a published Know Issue?) is there a workaround using the e.g. the Metadata Api? (I used the Tooling API here to get field ids to prepolate Fields on Standard Layouts).

**Comment by up2go-rsoesemann** [comment]
@afawcett I have no experience on how to write IdeaExchange entries with a high chance to get implemented in the next 5 years ;-). Would you be able to help me formulate an Ideaexchange entry for that one? (How to formulate what we want, describe the layers involed (our code, your wrapper))...

**Comment by afawcett** [comment]
**Title:** Functional parity between Setup menu access to Custom Objects and Tooling API access

**Background:** As a non-admin user you can go to the Setup menu and review Custom Objects. If with the same user you, you make an API call to the Tooling API query operation to do the same is performed and error 'yyyyyyyy' is given (see case XXXXXX). This behaviour is inconsistent.

**Solution Implications:** API's like the Tooling API and Metadata API allow developers to build tools that help users do more in less time by automating Setup tasks or reducing setup time for partner or custom application solutions. Not being able to query Custom Objects without users of such tools being admins is a serious inhibitor to this objective. 

**Ask:** Please allow query of the CustomObject object via the Tooling API query method without the user needing to be an administrator. As noted above, this behaviour is inconsistent with what the user perform by simply clicking on the Setup menu and navigating to the Objects menu item.

**Comment by afawcett** [comment]
Hows that?

**Comment by afawcett** [comment]
BTW, you can query this from Apex SOQL now.... https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm

(blog on its way, as i'm finding a few other useful objects that can now be queried! :+1: )

**Comment by up2go-rsoesemann** [comment]
@afawcett that awesome. Thanks a lot for formulating the idea text. Here is the idea. 

**[IdeaExchange: Functional parity between Setup menu + Tooling API to access Custom Objects](https://success.salesforce.com/ideaView?id=08730000000Lf4YAAS)**

I will also share it via Twitter and kindly ask you to pass it to the relevant persons at Salesforce.com that you mentioned in one of your ealier comments.

**Comment by up2go-rsoesemann** [comment]
@afawcett Really we can query Field Ids with SOQL queries?! At least from looking at your link I didn't find out how. Really looking forward to you blog post!

**Comment by afawcett** [comment]
Ah ok, i did provide it as a template, not that i used xxxxx and yyyy above for you to replace with the actual error and case number. Sadly i don't think you can edit an idea text now, you may be able to delete it and add a new one though?

**Comment by up2go-rsoesemann** [comment]
@afawcett yes this was an accident. I had a version with replacements but then copied and saved with the wrong version :-(. My bad! I added a comment. Hope this will go through and Editing of ideas will be implemented soon.

**Comment by boog** [comment]
>BTW, you can query this from Apex SOQL now.... https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm

>(blog on its way, as i'm finding a few other useful objects that can now be queried! :+1: )

Andy - what do you mean by this - you're still linking to the tooling API - do you mean you can query it from the rest API or just that you can query the tooling API objects from APEX somehow? I'm trying to lookup the custom object id like this,

`select id from customobject where developername='promotion_activity' and namespaceprefix=''`

And getting the error for non-admins, what I'm after is getting the object id and field id for a custom object/field so that I can pass it to the filtered lookup salesforce popup window which requires the field id in the URL. Is this something you think you have a work-around for?

I was looking to see if you blogged about this but didn't see anything, I think I attended your session at Dreamforce btw ;)

**Comment by afawcett** [comment]
You can for sure query the EntityDefinition object from Apex SOQL, little known, but works. :+1:  Hope you enjoyed the session!

**Comment by BCS-Chris** [comment]
The EntityDefinition definitely retrieves the IDs and other metadata but there is an issue calling this query from an ApexClass. I get no records returned for a query against something I know works when run inside of the dev console. I cannot really tell if the EntityDefinition will be query-able by non-admin users until that is resolved.

**Comment by afawcett** [comment]
Very interesting @BCS-Chris thanks for sharing! :+1:

**Comment by boog** [comment]
Thanks guys I was able to get the field and object ids from EntityDefinition and FieldDefinition objects without admin access from the tooling rest API using the DurableId field. Only trick was the FieldDefinition.DurableId appears to be the object id joined with the custom field id with ".". Documentation also warns not to use DurableId as it could change in future API versions, but I'll risk it for now since I don't know of another way to get this value without view all data (admin) access.

**Comment by afawcett** [comment]
Ok sounds good. Question though, if your after the ID's to pre-populate fields via URL hacking, are you not worried about how the solution will work in Lighting Experience? Or is there some other use for field Id's that i'm missing? :+1:

**Comment by boog** [comment]
My use case is working in the lightning experience, although the url that I am displaying is from salesforce classic. I am URL hacking the FK lookup popup, when the FK is on a custom object and is filtered I need specify the fieldId in the URL.

**Comment by afawcett** [comment]
Ok thanks for the follow up, i didn't expect the field defaulting URL hack to still work in LEX tbh.

**Comment by willemmulder** [comment]
@BCS-Chris As it appears, there's only a few fields that can be queried. I do it (simplified) like this:

```
public static Map<String,List<String>> getFieldIdsByNameForSobjectType(SObjectType type, Set<String> fieldNames) {
    String objectTypeForQuery = type.getDescribe().getName().replace('__c', '');
    List<EntityDefinition> entityDefinitions = [SELECT Id, DurableId from EntityDefinition WHERE             DeveloperName = :strippedName AND NamespacePrefix = :namespacePrefix];
    for(String fieldName : fieldNames) {
        String fieldNameForQuery = fieldName.replace('__c', '');
        String fieldNamespacePrefix;
        if (fieldNameForQuery.contains('__')) {
            fieldNamespacePrefix = fieldNameForQuery.substringBefore('__');
            fieldNameForQuery = fieldNameForQuery.substringAfter('__');
        }
        if (fieldNamespacePrefix != null && fieldNamespacePrefix != '') {
            fieldDefinitions = [SELECT Id, DeveloperName, NamespacePrefix, DurableId FROM FieldDefinition WHERE EntityDefinitionId = :entityDefinitionId AND DeveloperName = :fieldNameForQuery AND NamespacePrefix = :fieldNamespacePrefix];
        } else {
            fieldDefinitions = [SELECT Id, DeveloperName, NamespacePrefix, DurableId FROM FieldDefinition WHERE EntityDefinitionId = :entityDefinitionId AND DeveloperName = :fieldNameForQuery];
        }
    }
}
```
