### ISSUE TITLE
Field "modifiers" in tableDeclaration in SymbolTable is always empty

### ISSUE THREAD

**Issue by Likhovid** [afawcett/apex-toolingapi#23]
Hi!

When I retrieve a SymbolTable of an Apex class, the field "modifiers" in tableDeclaration is always empty. When I have "public virtual class ..." or "public with sharing class ..." - no matter it's always empty. The class is valid.

All other fields like constructors, methods and properties I retrieve without any problems (with their modifiers  as well).

Thank you,
Liudmila

**Comment by afawcett** [comment]
The SymbolTable is only filled in when you use ApexClassMember as part of a workspace. In other words the class has to have been compiled.
