### ISSUE TITLE
Unable to get the type of List/Set/Map added as parameter to a method

### ISSUE THREAD

**Issue by tquilapratyush** [afawcett/apex-toolingapi#32]
Hi Andy

I can see that the Parameter class has only two variable defined i.e. name and type. This works fine for any primitive data types but doesn't work well for any collection parameters as there isn't any reference for the type of collection parameter. 

For e.g. if a method is defined as: 
public void exampleMethod(List(String) paramStr, List(sObject) sObjects) { 
// Sorry, wasn't able to specify it as List<>
}

When I'm trying to retrieve the parameters for the method using SymbolTable, I'm able to get Parameter as:
(Parameter:[name=paramStr, type=LIST],
Parameter:[name=sObjects, type=LIST])

Is there any way I can get the type of Lists (i.e. List(String) or List(sObject)) in this example? It would be really helpful if you could let me know any other property that I'm missing over here.

Thanks in advance.

**Comment by afawcett** [comment]
Sadly the Salesforce Tooling API does not expose this, so there is nothing this wrapper can do about this. Worth raising on Ideas Exchange i would say!
