### ISSUE TITLE
Invalid conversion from runtime type List<ToolingAPIWSDL.sObject_x> to List<ToolingAPIWSDL.CustomObject>

### ISSUE THREAD

**Issue by rdehler** [afawcett/apex-toolingapi#36]
I tried to convert this sample to using the WSDL:
http://andyinthecloud.com/2014/01/05/querying-custom-object-and-field-ids-via-tooling-api/

		String objectName = 'Job_Activity';
		String fieldName = 'Order_Line';
		ToolingAPI toolingAPI = new ToolingAPI();
		List<ToolingAPIWSDL.CustomObject> customObjects = (List<ToolingAPIWSDL.CustomObject>)
     		toolingAPI.query('Select Id, DeveloperName, NamespacePrefix From CustomObject Where DeveloperName = \''+objectName+'\'').records;

		ToolingAPIWSDL.CustomObject customObject = customObjects[0];
		Id customObjectId = customObject.Id;
		List<ToolingAPIWSDL.CustomField> customFields = (List<ToolingAPIWSDL.CustomField>)
		     toolingAPI.query('Select Id, DeveloperName, NamespacePrefix, TableEnumOrId From CustomField Where DeveloperName = \''+fieldName+'\' and TableEnumOrId = \'' + customObjectId + '\'').records;

Upon trying to run this, I get:

     Invalid conversion from runtime type List<ToolingAPIWSDL.sObject_x> to List<ToolingAPIWSDL.CustomObject>

Am I missing something obvious?

**Comment by rdehler** [comment]
Replace with this and it works, FYI @afawcett 

		List<ToolingAPIWSDL.sObject_x> customObjects = (List<ToolingAPIWSDL.sObject_x>)
     		toolingAPI.query('Select Id, DeveloperName, NamespacePrefix From CustomObject Where DeveloperName = \''+objectName+'\'').records;

		ToolingAPIWSDL.sObject_x customObject = customObjects[0];
		Id customObjectId = customObject.Id;
		List<ToolingAPIWSDL.sObject_x> customFields = (List<ToolingAPIWSDL.sObject_x>)
		     toolingAPI.query('Select Id, DeveloperName, NamespacePrefix, TableEnumOrId From CustomField Where DeveloperName = \''+fieldName+'\' and TableEnumOrId = \'' + customObjectId + '\'').records;

**Comment by afawcett** [comment]
Thanks @rdehler, speaking with @dancinllama recently we feel we may want to return to the REST API wrapper approach, now that it appears to support bulk. Sorry for the confusion in the meantime.
