### ISSUE TITLE
Create Call INVALID_TYPE: Must send a concrete entity type

### ISSUE THREAD

**Issue by ForceComDeveloper** [afawcett/apex-toolingapi#37]
Hello,

I have an issue while trying to create ApexClassMember :
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_TYPE: Must send a concrete entity type. faultcode=sf:INVALID_TYPE faultactor=

Here is the code :
`
List<ToolingAPIWSDL.ApexClassMember> lACM = new List<ToolingAPIWSDL.ApexClassMember>();
    for(ToolingAPI.ApexClass aAC : apexClasses){ // ApexClasses are previously fetched with a query call which is ok
      ToolingAPIWSDL.ApexClassMember aACM = new ToolingAPIWSDL.ApexClassMember();
      aACM.Body = aAC.Body;
      aACM.ContentEntityId = aAC.Id;
      aACM.MetadataContainerId = aSR.id; // Come from
      lACM.add(aACM);
}
tooling.create(lACM); // This call generate the error
`

Is there anything wrong with the code ?
How should I do ?

Regards

**Comment by afawcett** [comment]
Its likely because its not passing xsi:type="ApexClassMember" when the ApexClassMember is serialised to XML. The SOAP edition of this wrapper is still partly complete by the looks of it. I would recommend you take a look at the REST edition branch, https://github.com/afawcett/apex-toolingapi/tree/apex-toolingapi-rest/src/classes.

**Comment by ForceComDeveloper** [comment]
Ok sure,

The main reason why I do not want to use the rest api for this feature is I
cannot create multiple element with one callout using the rest.
What changes has to be done to make it works ?
I can do the development and create a pull request if you explain me

**Comment by afawcett** [comment]
If you take a look at the types in the Apex Metadata API, MetadataService.cls you'll see a **type** member variable [defined](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls#L8373), also needed is **type_att_info** as defined [here](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls#L8469).

**Comment by ForceComDeveloper** [comment]
Ok thanks,
I will try a pull request and see with you is there are no side effects

**Comment by ForceComDeveloper** [comment]
Bonjour afawcett/apex-toolingapi,
Sebastien Colladon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/z8pJaH/haq/?hg=BLWDpeq7cT pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=5746a04e&email=reply@reply.github.com.&hg=BLWDpeq7cT
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by ForceComDeveloper** [comment]
Bonjour afawcett/apex-toolingapi,
Sebastien Colladon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/z8pJaH/xlt/?hg=BLWDpeq7cT pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=7e5c3aa2&email=reply@reply.github.com.&hg=BLWDpeq7cT
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
