### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by zen4orce-mehulmakwana** [afawcett/apex-toolingapi#44]
No Reply..........!!!

**Comment by afawcett** [comment]
Can you include the debug log? That should include the XML being sent to the server and might help debug whats going on here. Thanks!

**Comment by zen4orce-mehulmakwana** [comment]
Thanks for reply, 
I have Attached Debug Log kindly have a look into it.
[apex-07L2800000J7DV8EAN.txt](https://github.com/afawcett/apex-toolingapi/files/283465/apex-07L2800000J7DV8EAN.txt)

**Comment by zen4orce-mehulmakwana** [comment]
I did some change in my code,but still have some error
Error: "Line: 4449, Column: 1
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: null; nested exception is: java.lang.NullPointerException faultcode=soapenv:Server faultactor="

1) My Code : [myCode.txt](https://github.com/afawcett/apex-toolingapi/files/284064/myCode.txt)
 2) Debug log File:  [myLog.txt](https://github.com/afawcett/apex-toolingapi/files/284068/myLog.txt)

Thanks
Mehul

**Comment by afawcett** [comment]
@zen4orce-mehulmakwana i'm confused? You renamed the title of this issue and don't appear to have responded to my last question?
