### ISSUE TITLE
References of methods from Symbol Table  = null

### ISSUE THREAD

**Issue by Konstryktor** [afawcett/apex-toolingapi#48]
Hi, Andrew! Thank you for your tool.

 I want to get all references and external references of Apex Class method. My code:
`    
    ToolingAPIWSDL.SforceService toolingService = new ToolingAPIWSDL.SforceService();
    toolingService.SessionHeader = new ToolingAPIWSDL.SessionHeader_element();
    toolingService.SessionHeader.SessionId = UserInfo.getSessionId();
    toolingService.endpoint_x = URL.getSalesforceBaseUrl().toExternalForm() + '/services/Soap/T/33.0';

    ToolingAPIWSDL.QueryResult result = toolingService.query('select Id, Name, symbolTable from     ApexClass WHERE Name Like \'MyApexClass\'');
    for(ToolingAPIWSDL.sObject_x acx : result.records) {
        System.debug(acx.symbolTable.methods);
}`

MyApexClass:
`public with sharing class MyApexClass {

    private void testA(){}

    public void testB(){
        testA();
    }
}`

But in all methods I get references = null (really It should not be? because I call testA() method in testB()):

18:04:16:245 USER_DEBUG [8]|DEBUG|(Method:[apex_schema_type_info=(urn:tooling.soap.sforce.com, true, false), field_order_type_info=(location, modifiers, name, references, type_x, visibility, parameters, returnType), location=Position:[apex_schema_type_info=(urn:tooling.soap.sforce.com, true, false), column=18, column_type_info=(column, urn:tooling.soap.sforce.com, null, 1, 1, false), field_order_type_info=(column, line), line=3, line_type_info=(line, urn:tooling.soap.sforce.com, null, 1, 1, false)], location_type_info=(location, urn:tooling.soap.sforce.com, Position, 1, 1, false), modifiers=(private), modifiers_type_info=(modifiers, urn:tooling.soap.sforce.com, string, 0, -1, false),**name=testA,**name_type_info=(name,** urn:tooling.soap.sforce.com, string, 1, 1, false), parameters=null, parameters_type_info=(parameters, urn:tooling.soap.sforce.com, Parameter, 0, -1, false), **references=null,** references_type_info=(references, urn:tooling.soap.sforce.com, Position, 0, -1, false), returnType=void, returnType_type_info=(returnType, urn:tooling.soap.sforce.com, string, 1, 1, false), type_x=null, type_x_type_info=(type, urn:tooling.soap.sforce.com, string, 1, 1, false), visibility=Private, visibility_type_info=(visibility, urn:tooling.soap.sforce.com, SymbolVisibility, 1, 1, false)], Method:[apex_schema_type_info=(urn:tooling.soap.sforce.com, true, false), field_order_type_info=(location, modifiers, name, references, type_x, visibility, parameters, returnType), location=Position:[apex_schema_type_info=(urn:tooling.soap.sforce.com, true, false), column=17, column_type_info=(column, urn:tooling.soap.sforce.com, null, 1, 1, false), field_order_type_info=(column, line), line=6, line_type_info=(line, urn:tooling.soap.sforce.com, null, 1, 1, false)], location_type_info=(location, urn:tooling.soap.sforce.com, Position, 1, 1, false), modifiers=(public), modifiers_type_info=(modifiers, urn:tooling.soap.sforce.com, string, 0, -1, false), name=testB, name_type_info=(name, urn:tooling.soap.sforce.com, string, 1, 1, false), parameters=null, parameters_type_info=(parameters, urn:tooling.soap.sforce.com, Parameter, 0, -1, false), references=null, references_type_info=(references, urn:tooling.soap.sforce.com, Position, 0, -1, false), returnType=void, returnType_type_info=(returnType, urn:tooling.soap.sforce.com, string, 1, 1, false), type_x=null, type_x_type_info=(type, urn:tooling.soap.sforce.com, string, 1, 1, false), visibility=Public, visibility_type_info=(visibility, urn:tooling.soap.sforce.com, SymbolVisibility, 1, 1, false)])

**Comment by Konstryktor** [comment]
I am sorry, I found my error. [The SymbolTable returned from ApexClass does not contain references; to retrieve a SymbolTable with references](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_apexclass.htm), use ApexClassMember. But can we create ApexClassMember using this wrapper?

**Comment by afawcett** [comment]
Ah great, glad you found that. Yes, the Apex UML tool does this, see UmlService.cls, https://github.com/afawcett/apex-umlcanvas

**Comment by Konstryktor** [comment]
Thank you very much, Andrew! I ger SymbolTable and all references.  But I have [small problem](http://salesforce.stackexchange.com/questions/136309/why-in-all-apexclassmember-i-have-metadatacontainerid-null)? Can you help me with it?
