### ISSUE TITLE
Getting WorkflowOutboundMessage Id

### ISSUE THREAD

**Issue by mikesobczak** [afawcett/apex-toolingapi#51]
I've been trying the API out.  I would like to use it to get the Id of a Workflow rule.  How would I accomplish that?

**Comment by afawcett** [comment]
You should be able to run a SOQL query against this object and obtain the ID, https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_workflowoutboundmessage.htm
