### ISSUE TITLE
Code Coverage support

### ISSUE THREAD

**Issue by afawcett** [afawcett/apex-toolingapi#8]

**Comment by ghost** [comment]
Can anyone provide me the test class for ToolingAPI.cls?

**Comment by afawcett** [comment]
If you are using the SOAP version (default branch)...

https://github.com/afawcett/apex-toolingapi/blob/master/src/classes/ToolingAPIWSDLTest.cls

If you are using the REST version (separate branch)...

https://github.com/afawcett/apex-toolingapi/blob/apex-toolingapi-rest/src/classes/ToolingAPITest.cls
